services:
  postgres:
    image: postgres:16-alpine
    container_name: tradingsystem-postgres
    environment:
      POSTGRES_DB: tradingsystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
      container_name: pgadmin_main
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - postgres
  # Redis will be added in later phases
  # Kafka/Redpanda will be added in Phase 2

volumes:
  postgres_data: